name: Build archlinux kernel
permissions: write-all

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      _cpusched:
        required: false
        type: string

  workflow_dispatch: # on button click
      inputs:
        type:
          required: true
          type: string
        _cpusched:
          required: false
          type: string

env:
  _distro: "Arch"
  _waydroid: "true"
  _processor_opt: "generic"
  _git_mirror: "github.com"
  PKGDEST: "/tmp/linux-tkg"
  _debugdisable: "true"
  _noccache: "true"
  _STRIP: "true"
  _ftracedisable: "true"
  _kernel_on_diet: "true"
  _kernel_work_folder: "/tmp"
  _kernel_source_folder: "/tmp"
  # _modprobeddb: "true"
  _modprobeddb_db_path: ${{ github.workspace }}/modprobed.db
  _custom_pkgbase: linux-tkg-${{ inputs._cpusched }}

jobs:
  build-kernel:
    env:
      _cpusched: ${{ inputs._cpusched }}

    if: inputs.type == 'build'
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      # We need to install git so the checkout is done with it
      - name: Update mirrorlist
        run: |
          pacman -Sy --noconfirm reflector
          reflector --latest 50 --protocol http,https --sort rate --save /etc/pacman.d/mirrorlist

      - name: Install git
        run: pacman -Syu --noconfirm git

      - name: Checkount linux-tkg
        uses: actions/checkout@v4.1.1
        with:
          repository: 'Frogging-Family/linux-tkg'

      # 1. Install deps needed for building and sudo
      # 2. create a user "user" and give it passwordless sudo
      #    and necessary permissions
      #    because makepkg absolutely refuses to run as root
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R ..
          chown user -R /tmp

      # - name: "[debug] make dummy modprobed-db file for faster ci"
      #   run: |
      #     touch "${_modprobeddb_db_path}"
      #     echo "${_modprobeddb_db_path}"

      - name: Compile Kernel
        run: su user -c "yes '' | makepkg --noconfirm -s"
        # run: |
        #   mkdir -p "$PKGDEST"
        #   echo "test" > "$PKGDEST"/linux-$_cpusched.pkg.tar.zst

      - name: rename kernel config
        run: mv kernelconfig.new kernelconfig.arch.${{ env._cpusched }}.txt

      - uses: actions/upload-artifact@v4
        with:
          name: arch-kernel-packages-${{ env._cpusched }}
          path: |
            ${{ env.PKGDEST }}/linux*.pkg.tar.zst
            kernelconfig*.txt

  build-database:
    env:
      arch_repo_dir: "archlinux/main/x86_64"

    if: inputs.type == 'database'
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    steps:
      - name: Update mirrorlist
        run: |
          pacman -Sy --noconfirm reflector
          reflector --latest 50 --protocol http,https --sort delay --save /etc/pacman.d/mirrorlist

      - name: Install dependencies
        run: pacman -Syu --noconfirm git

      - name: Checkount linux-tkg
        uses: actions/checkout@v4.1.1

      - name: Post checkuot setup
        run: |
          git config --global --add safe.directory `pwd`
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Update package list database
        run: |
          for package in "${{ env.arch_repo_dir }}"/*.pkg.tar.zst; do
            echo "Processing package: $package"
            # Create a detached signature.
            rm -f "${package}".sig 
            gpg --batch --use-agent --output "${package}".sig --detach-sig "${package}"
          done
          repo-add --sign "${{ env.arch_repo_dir }}/linux-tkg.db.tar.gz"  ${{ env.arch_repo_dir }}/*.pkg.tar.zst
          rm ${{ env.arch_repo_dir }}/linux-tkg.db ${{ env.arch_repo_dir }}/linux-tkg.db.sig ${{ env.arch_repo_dir }}/linux-tkg.files ${{ env.arch_repo_dir }}/linux-tkg.files.sig
          cp ${{ env.arch_repo_dir }}/linux-tkg.db.tar.gz ${{ env.arch_repo_dir }}/linux-tkg.db
          cp ${{ env.arch_repo_dir }}/linux-tkg.db.tar.gz.sig ${{ env.arch_repo_dir }}/linux-tkg.db.sig
          cp ${{ env.arch_repo_dir }}/linux-tkg.files.tar.gz ${{ env.arch_repo_dir }}/linux-tkg.files
          cp ${{ env.arch_repo_dir }}/linux-tkg.files.tar.gz.sig ${{ env.arch_repo_dir }}/linux-tkg.files.sig
        
      - name: Commit updated package list database
        run: |
          git add .
          git commit -m "Push updated package list database"
          git pull --rebase
          git push
