name: Build & Release Latest Kernel
on:
  schedule:
    - cron: '15 */12 * * *' # “At minute 15 past every 12th hour.”
  workflow_dispatch:
    
env:
  max_old_release: "8" # Two for each scheduler
  arch_main_x86_64: "linux-tkg-repo/archlinux/main/x86_64"
  arch_archive_x86_64: "linux-tkg-repo/archlinux/archive/x86_64"
  debian_main_x86_64: "linux-tkg-repo/debian/main/x86_64"
  debian_archive_x86_64: "linux-tkg-repo/debian/archive/x86_64"
  fedora_main_x86_64: "linux-tkg-repo/fedora/main/x86_64"
  fedora_archive_x86_64: "linux-tkg-repo/fedora/archive/x86_64"

jobs:
  check-for-newer-kernel:
    runs-on: ubuntu-latest
    outputs:
      new_kernel: ${{ steps.check_for_new_kernel.outputs.new_kernel }}
      latest_kernel: ${{ steps.check_for_new_kernel.outputs.latest_kernel }}
    steps:
      - name: Checkount linux-tkg
        uses: actions/checkout@v3.0.2
      # Get latest release in repo, so we compare its version
      # with the latest kernel available so far
      - name: Get latest release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
        # it fails when there's no release
        continue-on-error: true
      - name: Get latest kernel version
        id: check_for_new_kernel
        run: |
          chmod +x ./.github/get_latest_kver.sh
          ./.github/get_latest_kver.sh
          latest_kernel="$(cat .github/latest-kernel)"
          echo "latest_kernel=$latest_kernel" >> $GITHUB_OUTPUT
          new_kernel=0
          [[ "$latest_kernel" != "$latest_release" ]] || new_kernel=$?
          echo "new_kernel=$new_kernel"
          echo "new_kernel=$new_kernel" >> $GITHUB_OUTPUT
        env:
          latest_release: ${{ steps.latest_release.outputs.release }}

  build:
    strategy:
      fail-fast: false
      matrix:
        _cpusched: [bore, eevdf, pds, bmq]
        os: [arch, ubuntu, fedora]
    uses: ./.github/workflows/builder-dispatcher.yml
    with:
      _cpusched: ${{ matrix._cpusched }}
      os: ${{ matrix.os }}
    needs: [check-for-newer-kernel]
    if: |
      github.ref == 'refs/heads/main' &&
      needs.check-for-newer-kernel.outputs.new_kernel == '0'

  make-release:
    runs-on: ubuntu-latest
    needs:
      - "check-for-newer-kernel"
      - "build"
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4

      - name: Make new release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ needs.check-for-newer-kernel.outputs.latest_kernel }}
          prerelease: false
          title: "[experimental] ${{ needs.check-for-newer-kernel.outputs.latest_kernel }}"
          files: |
            ${{ github.workspace }}/arch-kernel-packages-*/**
            ${{ github.workspace }}/ubuntu-kernel-packages-*/**
            ${{ github.workspace }}/fedora-kernel-packages-*/**

      - name: Checkount linux-tkg
        uses: actions/checkout@v4
        with:
          path: linux-tkg-repo

      - name: Delete old kernel
        run: |
          # Set variable
          max_files=${{ env.max_old_release }}

          # Function to manage files in a specific directory
          manage_archive_directory() {
            local directory="$1"
            local filter_pattern="$2"
            local action_commands="$3"

            files=($(ls -1 "$directory" | eval "$filter_pattern" | sort))
          
            if [ "${#files[@]}" -gt "$max_files" ]; then
              excess_files=( "${files[@]:$(($max_files - 4))}" )
              for file in "${excess_files[@]}"; do
                eval "$action_commands"
                echo "Managing archived kernel file in $directory: $file"
              done
              echo "Finished managing files in $directory matching pattern: $filter_pattern"
            fi
          }
          
          # Main script logic

          # Create directories if they don't exist
          mkdir -p \
            ${{ env.arch_main_x86_64 }} \
            ${{ env.arch_archive_x86_64 }} \
            ${{ env.debian_main_x86_64 }} \
            ${{ env.debian_archive_x86_64 }} \
            ${{ env.fedora_main_x86_64 }} \
            ${{ env.fedora_archive_x86_64 }}

          # Manage each directory with its specific filter pattern and action commands
          manage_archive_directory  "${{ env.arch_archive_x86_64 }}"      "grep linux | grep -v headers"      "rm -f '$directory/$file'"
          manage_archive_directory  "${{ env.arch_archive_x86_64 }}"      "grep linux | grep headers"         "rm -f '$directory/$file'"
          manage_archive_directory  "${{ env.debian_archive_x86_64 }}"    "grep linux-image"                  "rm -f '$directory/$file'"
          manage_archive_directory  "${{ env.debian_archive_x86_64 }}"    "grep linux-headers"                "rm -f '$directory/$file'"
          manage_archive_directory  "${{ env.fedora_archive_x86_64 }}"    "grep kernel | grep -v devel"       "rm -f '$directory/$file'"
          manage_archive_directory  "${{ env.fedora_archive_x86_64 }}"    "grep kernel-devel"                 "rm -f '$directory/$file'"

          manage_archive_directory  "${{ env.arch_main_x86_64 }}"         "grep linux | grep -v headers"      "mv -f '$directory/$file' ${{ env.arch_archive_x86_64 }}"
          manage_archive_directory  "${{ env.arch_main_x86_64 }}"         "grep linux | grep headers"         "mv -f '$directory/$file' ${{ env.arch_archive_x86_64 }}"
          manage_archive_directory  "${{ env.debian_main_x86_64 }}"       "grep linux-image"                  "mv -f '$directory/$file' ${{ env.debian_archive_x86_64 }}"
          manage_archive_directory  "${{ env.debian_main_x86_64 }}"       "grep linux-headers"                "mv -f '$directory/$file' ${{ env.debian_archive_x86_64 }}"
          manage_archive_directory  "${{ env.fedora_main_x86_64 }}"       "grep kernel | grep -v devel"       "mv -f '$directory/$file' ${{ env.fedora_archive_x86_64 }}"
          manage_archive_directory  "${{ env.fedora_main_x86_64 }}"       "grep kernel-devel"                 "mv -f '$directory/$file' ${{ env.fedora_archive_x86_64 }}"

      - name: Copy new kernel release
        run: |
          # Create directories if they don't exist
          mkdir -p \
            ${{ env.arch_main_x86_64 }} \
            ${{ env.debian_main_x86_64 }} \
            ${{ env.fedora_main_x86_64 }}

          cp  ${{ github.workspace }}/arch-kernel-packages-bmq/tmp/linux-tkg/linux*.pkg.tar.zst      ${{ env.arch_main_x86_64 }}
          cp  ${{ github.workspace }}/arch-kernel-packages-bore/tmp/linux-tkg/linux*.pkg.tar.zst     ${{ env.arch_main_x86_64 }}
          cp  ${{ github.workspace }}/arch-kernel-packages-eevdf/tmp/linux-tkg/linux*.pkg.tar.zst    ${{ env.arch_main_x86_64 }}
          cp  ${{ github.workspace }}/arch-kernel-packages-pds/tmp/linux-tkg/linux*.pkg.tar.zst      ${{ env.arch_main_x86_64 }}
          cp  ${{ github.workspace }}/ubuntu-kernel-packages-bmq/DEBS/*.deb        ${{ env.debian_main_x86_64 }}
          cp  ${{ github.workspace }}/ubuntu-kernel-packages-bore/DEBS/*.deb       ${{ env.debian_main_x86_64 }}
          cp  ${{ github.workspace }}/ubuntu-kernel-packages-eevdf/DEBS/*.deb      ${{ env.debian_main_x86_64 }}
          cp  ${{ github.workspace }}/ubuntu-kernel-packages-pds/DEBS/*.deb        ${{ env.debian_main_x86_64 }}
          #cp ${{ github.workspace }}/fedora-kernel-packages-bmq/RPMS/*.rpm        ${{ env.fedora_main_x86_64 }} # temporarily disable fedora
          #cp ${{ github.workspace }}/fedora-kernel-packages-bore/RPMS/*.rpm       ${{ env.fedora_main_x86_64 }} # temporarily disable fedora
          #cp ${{ github.workspace }}/fedora-kernel-packages-eevdf/RPMS/*.rpm      ${{ env.fedora_main_x86_64 }} # temporarily disable fedora
          #cp ${{ github.workspace }}/fedora-kernel-packages-pds/RPMS/*.rpm        ${{ env.fedora_main_x86_64 }} # temporarily disable fedora

      - name: Commit new kernel release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Push updated package list database"
          git pull --rebase
          git push

  build-database:
    strategy:
      fail-fast: false
      matrix:
        #os: [arch, ubuntu, fedora]
        os: [arch, ubuntu] # temporarily disable fedora
    uses: ./.github/workflows/database-builder-dispatcher.yml
    with:
      os: ${{ matrix.os }}
    needs:
      - "check-for-newer-kernel"
      - "build"
      - "make-release"