name: builder dispatcher
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      _cpusched:
        required: true
        type: string

jobs:
  dispatch-to-fedora:
    uses: ./.github/workflows/fedora-builder.yml
    with:
      _cpusched: ${{ inputs._cpusched }}
    if: inputs.os == 'fedora'

  dispatch-to-ubuntu:
    uses: ./.github/workflows/ubuntu-builder.yml
    with:
      _cpusched: ${{ inputs._cpusched }}
    if: inputs.os == 'ubuntu'

  dispatch-to-arch:
    uses: ./.github/workflows/arch-builder.yml
    with:
      _cpusched: ${{ inputs._cpusched }}
    if: inputs.os == 'arch'
