name: database builder dispatcher

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      os:
        required: true
        type: string

env:
  # Set variables for clarity and maintainability
  archlinux_repo_dir: "archlinux/x86_64"
  fedora_repo_dir: "fedora/x86_64"
  ubuntu_repo_dir: "debian"
  ubuntu_repo_dir_tmp: "debian/tmp"
  ubuntu_package_dir: "debian/packages"

jobs:
  dispatch-to-fedora:
    if: inputs.os == 'fedora'
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Install dependencies
        run: dnf install git createrepo -y
      - name: Checkount linux-tkg-repo
        uses: actions/checkout@v4
      - name: fix git folder ownership
        run: git config --global --add safe.directory `pwd`
      - name: run git status
        run: git status
      - name: Update package list database
        run: createrepo ${{ env.fedora_repo_dir }}
      - name: Add git safe directory
        run: git config --global --add safe.directory /__w/linux-tkg-repo/linux-tkg-repo
      - name: Push updated package list database
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Push updated package list database

  dispatch-to-ubuntu:
    if: inputs.os == 'ubuntu'
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y dpkg-dev gpg debarchiver
      - name: Checkount linux-tkg-repo
        uses: actions/checkout@v4
      - name: Update package list database
        run: |
          # Setup environment
          mkdir -p ${{ env.ubuntu_package_dir }} ${{ env.ubuntu_repo_dir_tmp }}
          mv ${{ env.ubuntu_package_dir }} ${{ env.ubuntu_repo_dir_tmp }} || echo No Package avaliable
          # Setup databases
          mv ${{ env.ubuntu_repo_dir }}/stable ${{ env.ubuntu_repo_dir }}/lenny
          ln -s ${{ env.ubuntu_repo_dir }}/lenny ${{ env.ubuntu_repo_dir }}/stable
          # Create the databases
          debarchiver --addoverride --autoscanall --configfile ./.github/ubuntu_repo.conf
          # Post cleanup
          rm -rf ${{ env.ubuntu_repo_dir_tmp }}
          # Post setup
          rm -rf ${{ env.ubuntu_repo_dir }}/stable
          mv ${{ env.ubuntu_repo_dir }}/lenny ${{ env.ubuntu_repo_dir }}/stable
      - name: Add git safe directory
        run: git config --global --add safe.directory /__w/linux-tkg-repo/linux-tkg-repo
      - name: Push updated package list database
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Push updated package list database

  dispatch-to-arch:
    if: inputs.os == 'arch'
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Update mirrorlist
        run: |
          pacman -Sy --noconfirm reflector
          reflector --latest 50 --protocol http,https --sort rate --save /etc/pacman.d/mirrorlist
      - name: Install dependencies
        run: pacman -Syu --noconfirm git
      - name: Checkount linux-tkg
        uses: actions/checkout@v4
      - name: Update package list database
        run: |
          repo-add "${{ env.archlinux_repo_dir }}/linux-tkg.db.tar.gz"  ${{ env.archlinux_repo_dir }}/*.pkg.tar.zst
          rm ${{ env.archlinux_repo_dir }}/linux-tkg.db                 ${{ env.archlinux_repo_dir }}/linux-tkg.files
          cp ${{ env.archlinux_repo_dir }}/linux-tkg.db.tar.gz          ${{ env.archlinux_repo_dir }}/linux-tkg.db
          cp ${{ env.archlinux_repo_dir }}/linux-tkg.files.tar.gz       ${{ env.archlinux_repo_dir }}/linux-tkg.files
      - name: Add git safe directory
        run: git config --global --add safe.directory /__w/linux-tkg-repo/linux-tkg-repo
      - name: Push updated package list database
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Push updated package list database