name: database builder dispatcher
permissions: write-all

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      os:
        required: true
        type: string

jobs:
  dispatch-to-fedora:
    uses: ./.github/workflows/fedora-builder.yml
    with:
      type: 'database'
    if: inputs.os == 'fedora'

  dispatch-to-ubuntu:
    uses: ./.github/workflows/ubuntu-builder.yml
    with:
      type: 'database'
    if: inputs.os == 'ubuntu'

  dispatch-to-arch:
    uses: ./.github/workflows/arch-builder.yml
    with:
      type: 'database'
    if: inputs.os == 'arch'